
from pynput.keyboard import Key, Controller
import time

keyboard = Controller()

time.sleep(5)

for i in range(2, 101):
    keyboard.press(Key.ctrl_l)
    time.sleep(0.1)
    keyboard.press('g')
    time.sleep(0.1)
    keyboard.release(Key.ctrl_l)
    keyboard.release('g')
    time.sleep(0.1)
    keyboard.press(Key.enter)
    time.sleep(0.1)
    keyboard.release(Key.enter)
    time.sleep(3)
    keyboard.press('r')
    time.sleep(3)
    keyboard.press('r')
    time.sleep(10)
    keyboard.release('r')
    time.sleep(0.1)
    keyboard.press(Key.enter)
    time.sleep(0.1)
    keyboard.release(Key.enter)
    time.sleep(0.5)
    keyboard.press(Key.ctrl_l)
    time.sleep(0.1)
    keyboard.press('s')
    time.sleep(0.1)
    keyboard.release(Key.ctrl_l)
    keyboard.release('s')
    time.sleep(1)
    for char in str(i):
        keyboard.press(char)
        time.sleep(0.1)
        keyboard.release(char)
        time.sleep(0.1)
    keyboard.press(Key.tab)
    time.sleep(0.1)
    keyboard.release(Key.tab)
    time.sleep(0.1)
    keyboard.press(Key.down)
    time.sleep(0.1)
    keyboard.press(Key.down)
    time.sleep(0.1)
    keyboard.release(Key.down)
    time.sleep(0.1)
    keyboard.press(Key.enter)
    time.sleep(0.1)
    keyboard.release(Key.enter)
    time.sleep(1)
    keyboard.press(Key.tab)
    time.sleep(0.1)
    keyboard.press(Key.tab)
    time.sleep(0.1)
    keyboard.release(Key.tab)
    time.sleep(0.1)
    keyboard.press(Key.enter)
    time.sleep(0.1)
    keyboard.release(Key.enter)
    time.sleep(1)
